let Answers = [
  {
    Q1: "Which room are you looking to put plants in?",
    Q2: "What kind of light does this area get?",
    Q3: "What's your experience with plants?",
    Q4: "Do you have any pets or children?",
    Q5:
      "Do you travel often, or are you likely to forget watering your plants?",
    P1: "",
    P2: "",
    P3: "",
    P4: "",
    P5: "",
  },
  {
    Q1: "Living Room",
    Q2: "Indirect or filtered sunlight throughout the day",
    Q3: "Total plant savant and experienced plant-parent",
    Q4: "Yes",
    Q5: "Yes",
    P1: "Areca Palm",
    P2: "Table Palm",
    P3: "Succulents",
    P4: "Water Bamboo",
    P5: "Ruffled Fan Palm",
  },
  {
    Q1: "Living Room",
    Q2: "Indirect or filtered sunlight throughout the day",
    Q3: "Total plant savant and experienced plant-parent",
    Q4: "Yes",
    Q5: "No",
    P1: "Spider Plant",
    P2: "Areca Palm",
    P3: "Ferns",
    P4: "Maranta",
    P5: "Hypoestes",
  },
  {
    Q1: "Living Room",
    Q2: "Indirect or filtered sunlight throughout the day",
    Q3: "Total plant savant and experienced plant-parent",
    Q4: "Yes",
    Q5: "Sometimes",
    P1: "Rhapis Lady Palm",
    P2: "Succulent Bush",
    P3: "Carpet Sedum",
    P4: "Japanese Spindletree",
    P5: "Ruffled Fan Palm",
  },
  {
    Q1: "Living Room",
    Q2: "Indirect or filtered sunlight throughout the day",
    Q3: "Total plant savant and experienced plant-parent",
    Q4: "No",
    Q5: "Yes",
    P1: "Aloe Vera",
    P2: "Table Palm",
    P3: "Aglaonema",
    P4: "Succulents",
    P5: "Snake Plant",
  },
  {
    Q1: "Living Room",
    Q2: "Indirect or filtered sunlight throughout the day",
    Q3: "Total plant savant and experienced plant-parent",
    Q4: "No",
    Q5: "No",
    P1: "ZZ Plant",
    P2: "Anthurium",
    P3: "Philodendrons",
    P4: "Monstera",
    P5: "Fiddle Leaf Fig",
  },
  {
    Q1: "Living Room",
    Q2: "Indirect or filtered sunlight throughout the day",
    Q3: "Total plant savant and experienced plant-parent",
    Q4: "No",
    Q5: "Sometimes",
    P1: "Rhapis Lady Palm",
    P2: "Succulent Bush",
    P3: "Carpet Sedum",
    P4: "Snake Plant",
    P5: "Ruffled Fan Palm",
  },
  {
    Q1: "Living Room",
    Q2: "Indirect or filtered sunlight throughout the day",
    Q3: "Green thumb with few houseplants",
    Q4: "Yes",
    Q5: "Yes",
    P1: "Areca Palm",
    P2: "Table Palm",
    P3: "Succulents",
    P4: "Water Bamboo",
    P5: "Ruffled Fan Palm",
  },
  {
    Q1: "Living Room",
    Q2: "Indirect or filtered sunlight throughout the day",
    Q3: "Green thumb with few houseplants",
    Q4: "Yes",
    Q5: "No",
    P1: "Spider Plant",
    P2: "Areca Palm",
    P3: "Ferns",
    P4: "Maranta",
    P5: "Hypoestes",
  },
  {
    Q1: "Living Room",
    Q2: "Indirect or filtered sunlight throughout the day",
    Q3: "Green thumb with few houseplants",
    Q4: "Yes",
    Q5: "Sometimes",
    P1: "Rhapis Lady Palm",
    P2: "Succulent Bush",
    P3: "Carpet Sedum",
    P4: "Spider Plant",
    P5: "Ruffled Fan Palm",
  },
  {
    Q1: "Living Room",
    Q2: "Indirect or filtered sunlight throughout the day",
    Q3: "Green thumb with few houseplants",
    Q4: "No",
    Q5: "Yes",
    P1: "Areca Palm",
    P2: "Table Palm",
    P3: "Succulents",
    P4: "Water Bamboo",
    P5: "Ruffled Fan Palm",
  },
  {
    Q1: "Living Room",
    Q2: "Indirect or filtered sunlight throughout the day",
    Q3: "Green thumb with few houseplants",
    Q4: "No",
    Q5: "No",
    P1: "Monstera",
    P2: "Philodendrons",
    P3: "Syngonium",
    P4: "Money Plant",
    P5: "Anthurium",
  },
  {
    Q1: "Living Room",
    Q2: "Indirect or filtered sunlight throughout the day",
    Q3: "Green thumb with few houseplants",
    Q4: "No",
    Q5: "Sometimes",
    P1: "Monstera",
    P2: "Philodendrons",
    P3: "Syngonium",
    P4: "Money Plant",
    P5: "Anthurium",
  },
  {
    Q1: "Living Room",
    Q2: "Indirect or filtered sunlight throughout the day",
    Q3: "First time budding plant mom/dad",
    Q4: "Yes",
    Q5: "Yes",
    P1: "Areca Palm",
    P2: "Table Palm",
    P3: "Succulents",
    P4: "Water Bamboo",
    P5: "Ruffled Fan Palm",
  },
  {
    Q1: "Living Room",
    Q2: "Indirect or filtered sunlight throughout the day",
    Q3: "First time budding plant mom/dad",
    Q4: "Yes",
    Q5: "No",
    P1: "Spider Plant",
    P2: "Areca Palm",
    P3: "Ferns",
    P4: "Maranta",
    P5: "Hypoestes",
  },
  {
    Q1: "Living Room",
    Q2: "Indirect or filtered sunlight throughout the day",
    Q3: "First time budding plant mom/dad",
    Q4: "Yes",
    Q5: "Sometimes",
    P1: "Rhapis Lady Palm",
    P2: "Succulent Bush",
    P3: "Carpet Sedum",
    P4: "Japanese Spindletree",
    P5: "Ruffled Fan Palm",
  },
  {
    Q1: "Living Room",
    Q2: "Indirect or filtered sunlight throughout the day",
    Q3: "First time budding plant mom/dad",
    Q4: "No",
    Q5: "Yes",
    P1: "Areca Palm",
    P2: "Rhapis Lady Palm",
    P3: "Succulents",
    P4: "Water Bamboo",
    P5: "Ruffled Fan Palm",
  },
  {
    Q1: "Living Room",
    Q2: "Indirect or filtered sunlight throughout the day",
    Q3: "First time budding plant mom/dad",
    Q4: "No",
    Q5: "No",
    P1: "Monstera",
    P2: "Impatiens",
    P3: "Syngonium",
    P4: "Money Plant",
    P5: "Anthurium",
  },
  {
    Q1: "Living Room",
    Q2: "Indirect or filtered sunlight throughout the day",
    Q3: "First time budding plant mom/dad",
    Q4: "No",
    Q5: "Sometimes",
    P1: "Mosntera",
    P2: "Philodendrons",
    P3: "Syngonium",
    P4: "Money Plant",
    P5: "Anthurium",
  },
  {
    Q1: "Living Room",
    Q2: "Indirect or filtered sunlight throughout the day",
    Q3: "Most of my plants are dead :(",
    Q4: "Yes",
    Q5: "Yes",
    P1: "Areca Palm",
    P2: "Table Palm",
    P3: "Succulents",
    P4: "Water Bamboo",
    P5: "Ruffled Fan Palm",
  },
  {
    Q1: "Living Room",
    Q2: "Indirect or filtered sunlight throughout the day",
    Q3: "Most of my plants are dead :(",
    Q4: "Yes",
    Q5: "No",
    P1: "Rhapis Lady Palm",
    P2: "Table Palm",
    P3: "Succulents",
    P4: "Water Bamboo",
    P5: "Ruffled Fan Palm",
  },
  {
    Q1: "Living Room",
    Q2: "Indirect or filtered sunlight throughout the day",
    Q3: "Most of my plants are dead :(",
    Q4: "Yes",
    Q5: "Sometimes",
    P1: "Carpet Sedum",
    P2: "Maranta",
    P3: "Areca Palm",
    P4: "Table Palm",
    P5: "Water Bamboo",
  },
  {
    Q1: "Living Room",
    Q2: "Indirect or filtered sunlight throughout the day",
    Q3: "Most of my plants are dead :(",
    Q4: "No",
    Q5: "Yes",
    P1: "Rhapis Lady Palm",
    P2: "Succulent Bush",
    P3: "Carpet Sedum",
    P4: "Snake Plant",
    P5: "Ruffled Fan Palm",
  },
  {
    Q1: "Living Room",
    Q2: "Indirect or filtered sunlight throughout the day",
    Q3: "Most of my plants are dead :(",
    Q4: "No",
    Q5: "No",
    P1: "Ruffled Fan Palm",
    P2: "Impatiens",
    P3: "Succulents",
    P4: "Snake Plant",
    P5: "Syngonium",
  },
  {
    Q1: "Living Room",
    Q2: "Indirect or filtered sunlight throughout the day",
    Q3: "Most of my plants are dead :(",
    Q4: "No",
    Q5: "Sometimes",
    P1: "Areca Palm",
    P2: "Succulent Bush",
    P3: "Carpet Sedum",
    P4: "Snake Plant",
    P5: "Ruffled Fan Palm",
  },
  {
    Q1: "Living Room",
    Q2: "Bright direct sunlight 4-5 hours per day",
    Q3: "Total plant savant and experienced plant-parent",
    Q4: "Yes",
    Q5: "Yes",
    P1: "Herbs",
    P2: "Mini Tree Fern",
    P3: "Succulents",
    P4: "Gerbera",
    P5: "Petunia",
  },
  {
    Q1: "Living Room",
    Q2: "Bright direct sunlight 4-5 hours per day",
    Q3: "Total plant savant and experienced plant-parent",
    Q4: "Yes",
    Q5: "No",
    P1: "Herbs",
    P2: "Gerbera",
    P3: "Succulents",
    P4: "Chrysanthemum",
    P5: "Petunia",
  },
  {
    Q1: "Living Room",
    Q2: "Bright direct sunlight 4-5 hours per day",
    Q3: "Total plant savant and experienced plant-parent",
    Q4: "Yes",
    Q5: "Sometimes",
    P1: "Herbs",
    P2: "Gerbera",
    P3: "Succulents",
    P4: "Chrysanthemum",
    P5: "Petunia",
  },
  {
    Q1: "Living Room",
    Q2: "Bright direct sunlight 4-5 hours per day",
    Q3: "Total plant savant and experienced plant-parent",
    Q4: "No",
    Q5: "Yes",
    P1: "Jade",
    P2: "Succulents",
    P3: "Carpet Sedum",
    P4: "Rubber Plant",
    P5: "Snake Plant",
  },
  {
    Q1: "Living Room",
    Q2: "Bright direct sunlight 4-5 hours per day",
    Q3: "Total plant savant and experienced plant-parent",
    Q4: "No",
    Q5: "No",
    P1: "Jade",
    P2: "Crotons",
    P3: "Flowering Plants",
    P4: "Herbs",
    P5: "Succulents",
  },
  {
    Q1: "Living Room",
    Q2: "Bright direct sunlight 4-5 hours per day",
    Q3: "Total plant savant and experienced plant-parent",
    Q4: "No",
    Q5: "Sometimes",
    P1: "Jade",
    P2: "Crotons",
    P3: "Flowering Plants",
    P4: "Herbs",
    P5: "Succulents",
  },
  {
    Q1: "Living Room",
    Q2: "Bright direct sunlight 4-5 hours per day",
    Q3: "Green thumb with few houseplants",
    Q4: "Yes",
    Q5: "Yes",
    P1: "Herbs",
    P2: "Mini Tree Fern",
    P3: "Succulents",
    P4: "Gerbera",
    P5: "Petunia",
  },
  {
    Q1: "Living Room",
    Q2: "Bright direct sunlight 4-5 hours per day",
    Q3: "Green thumb with few houseplants",
    Q4: "Yes",
    Q5: "No",
    P1: "Herbs",
    P2: "Gerbera",
    P3: "Succulents",
    P4: "Chrysanthemum",
    P5: "Petunia",
  },
  {
    Q1: "Living Room",
    Q2: "Bright direct sunlight 4-5 hours per day",
    Q3: "Green thumb with few houseplants",
    Q4: "Yes",
    Q5: "Sometimes",
    P1: "Herbs",
    P2: "Gerbera",
    P3: "Succulents",
    P4: "Chrysanthemum",
    P5: "Petunia",
  },
  {
    Q1: "Living Room",
    Q2: "Bright direct sunlight 4-5 hours per day",
    Q3: "Green thumb with few houseplants",
    Q4: "No",
    Q5: "Yes",
    P1: "Jade",
    P2: "Succulents",
    P3: "Carpet Sedum",
    P4: "Rubber Plant",
    P5: "Snake Plant",
  },
  {
    Q1: "Living Room",
    Q2: "Bright direct sunlight 4-5 hours per day",
    Q3: "Green thumb with few houseplants",
    Q4: "No",
    Q5: "No",
    P1: "Jade",
    P2: "Crotons",
    P3: "Flowering Plants",
    P4: "Herbs",
    P5: "Succulents",
  },
  {
    Q1: "Living Room",
    Q2: "Bright direct sunlight 4-5 hours per day",
    Q3: "Green thumb with few houseplants",
    Q4: "No",
    Q5: "Sometimes",
    P1: "Jade",
    P2: "Crotons",
    P3: "Flowering Plants",
    P4: "Herbs",
    P5: "Succulents",
  },
  {
    Q1: "Living Room",
    Q2: "Bright direct sunlight 4-5 hours per day",
    Q3: "First time budding plant mom/dad",
    Q4: "Yes",
    Q5: "Yes",
    P1: "Herbs",
    P2: "Mini Tree Fern",
    P3: "Succulents",
    P4: "Gerbera",
    P5: "Petunia",
  },
  {
    Q1: "Living Room",
    Q2: "Bright direct sunlight 4-5 hours per day",
    Q3: "First time budding plant mom/dad",
    Q4: "Yes",
    Q5: "No",
    P1: "Herbs",
    P2: "Gerbera",
    P3: "Succulents",
    P4: "Chrysanthemum",
    P5: "Petunia",
  },
  {
    Q1: "Living Room",
    Q2: "Bright direct sunlight 4-5 hours per day",
    Q3: "First time budding plant mom/dad",
    Q4: "Yes",
    Q5: "Sometimes",
    P1: "Herbs",
    P2: "Gerbera",
    P3: "Succulents",
    P4: "Chrysanthemum",
    P5: "Petunia",
  },
  {
    Q1: "Living Room",
    Q2: "Bright direct sunlight 4-5 hours per day",
    Q3: "First time budding plant mom/dad",
    Q4: "No",
    Q5: "Yes",
    P1: "Jade",
    P2: "Succulents",
    P3: "Carpet Sedum",
    P4: "Rubber Plant",
    P5: "Snake Plant",
  },
  {
    Q1: "Living Room",
    Q2: "Bright direct sunlight 4-5 hours per day",
    Q3: "First time budding plant mom/dad",
    Q4: "No",
    Q5: "No",
    P1: "Jade",
    P2: "Crotons",
    P3: "Flowering Plants",
    P4: "Herbs",
    P5: "Succulents",
  },
  {
    Q1: "Living Room",
    Q2: "Bright direct sunlight 4-5 hours per day",
    Q3: "First time budding plant mom/dad",
    Q4: "No",
    Q5: "Sometimes",
    P1: "Jade",
    P2: "Crotons",
    P3: "Flowering Plants",
    P4: "Herbs",
    P5: "Succulents",
  },
  {
    Q1: "Living Room",
    Q2: "Bright direct sunlight 4-5 hours per day",
    Q3: "Most of my plants are dead :(",
    Q4: "Yes",
    Q5: "Yes",
    P1: "Herbs",
    P2: "Mini Tree Fern",
    P3: "Succulents",
    P4: "Gerbera",
    P5: "Petunia",
  },
  {
    Q1: "Living Room",
    Q2: "Bright direct sunlight 4-5 hours per day",
    Q3: "Most of my plants are dead :(",
    Q4: "Yes",
    Q5: "No",
    P1: "Herbs",
    P2: "Gerbera",
    P3: "Succulents",
    P4: "Chrysanthemum",
    P5: "Petunia",
  },
  {
    Q1: "Living Room",
    Q2: "Bright direct sunlight 4-5 hours per day",
    Q3: "Most of my plants are dead :(",
    Q4: "Yes",
    Q5: "Sometimes",
    P1: "Herbs",
    P2: "Gerbera",
    P3: "Succulents",
    P4: "Chrysanthemum",
    P5: "Petunia",
  },
  {
    Q1: "Living Room",
    Q2: "Bright direct sunlight 4-5 hours per day",
    Q3: "Most of my plants are dead :(",
    Q4: "No",
    Q5: "Yes",
    P1: "Jade",
    P2: "Succulents",
    P3: "Carpet Sedum",
    P4: "Rubber Plant",
    P5: "Snake Plant",
  },
  {
    Q1: "Living Room",
    Q2: "Bright direct sunlight 4-5 hours per day",
    Q3: "Most of my plants are dead :(",
    Q4: "No",
    Q5: "No",
    P1: "Crotons",
    P2: "Jade",
    P3: "Herbs",
    P4: "ZZ Plant",
    P5: "Succulents",
  },
  {
    Q1: "Living Room",
    Q2: "Bright direct sunlight 4-5 hours per day",
    Q3: "Most of my plants are dead :(",
    Q4: "No",
    Q5: "Sometimes",
    P1: "Jade",
    P2: "Crotons",
    P3: "ZZ Plant",
    P4: "Herbs",
    P5: "Succulents",
  },
  {
    Q1: "Living Room",
    Q2: "Not a lot of natural sunlight",
    Q3: "Total plant savant and experienced plant-parent",
    Q4: "Yes",
    Q5: "Yes",
    P1: "Table Palm",
    P2: "Rhapis Lady Palm",
    P3: "Impatiens",
    P4: "Water Bamboo",
    P5: "Maranta",
  },
  {
    Q1: "Living Room",
    Q2: "Not a lot of natural sunlight",
    Q3: "Total plant savant and experienced plant-parent",
    Q4: "Yes",
    Q5: "No",
    P1: "Spider Plant",
    P2: "Hypoestes",
    P3: "Rhapis lady Palm",
    P4: "Table Palm",
    P5: "Syngonium",
  },
  {
    Q1: "Living Room",
    Q2: "Not a lot of natural sunlight",
    Q3: "Total plant savant and experienced plant-parent",
    Q4: "Yes",
    Q5: "Sometimes",
    P1: "Ruffled Fan Palm",
    P2: "Rhapis Lady Palm",
    P3: "Table Palm",
    P4: "Water Bamboo",
    P5: "Maranta",
  },
  {
    Q1: "Living Room",
    Q2: "Not a lot of natural sunlight",
    Q3: "Total plant savant and experienced plant-parent",
    Q4: "No",
    Q5: "Yes",
    P1: "Aglaonema",
    P2: "Dieffenbachia",
    P3: "Money Plant",
    P4: "Syngonium",
    P5: "Table Palm",
  },
  {
    Q1: "Living Room",
    Q2: "Not a lot of natural sunlight",
    Q3: "Total plant savant and experienced plant-parent",
    Q4: "No",
    Q5: "No",
    P1: "Snake Plant",
    P2: "Hypoestes",
    P3: "Agalonema",
    P4: "Dieffenbachia",
    P5: "Syngonium",
  },
  {
    Q1: "Living Room",
    Q2: "Not a lot of natural sunlight",
    Q3: "Total plant savant and experienced plant-parent",
    Q4: "No",
    Q5: "Sometimes",
    P1: "Aglaonema",
    P2: "Money Plant",
    P3: "Dieffenbachia",
    P4: "English Ivy",
    P5: "Syngonium",
  },
  {
    Q1: "Living Room",
    Q2: "Not a lot of natural sunlight",
    Q3: "Green thumb with few houseplants",
    Q4: "Yes",
    Q5: "Yes",
    P1: "Table Palm",
    P2: "Calathea",
    P3: "Table Palm",
    P4: "Rhapis Lady Palm",
    P5: "Impatiens",
  },
  {
    Q1: "Living Room",
    Q2: "Not a lot of natural sunlight",
    Q3: "Green thumb with few houseplants",
    Q4: "Yes",
    Q5: "No",
    P1: "Ruffled Fan Palm",
    P2: "Maranta",
    P3: "Rhapis Lady Palm",
    P4: "Table Palm",
    P5: "Impatiens",
  },
  {
    Q1: "Living Room",
    Q2: "Not a lot of natural sunlight",
    Q3: "Green thumb with few houseplants",
    Q4: "Yes",
    Q5: "Sometimes",
    P1: "Areca Palm",
    P2: "Calathea",
    P3: "Rhapis Lady Palm",
    P4: "Table Palm",
    P5: "Water Bamboo",
  },
  {
    Q1: "Living Room",
    Q2: "Not a lot of natural sunlight",
    Q3: "Green thumb with few houseplants",
    Q4: "No",
    Q5: "Yes",
    P1: "Aglaonema",
    P2: "Dieffenbachia",
    P3: "Money Plant",
    P4: "Syngonium",
    P5: "Table Palm",
  },
  {
    Q1: "Living Room",
    Q2: "Not a lot of natural sunlight",
    Q3: "Green thumb with few houseplants",
    Q4: "No",
    Q5: "No",
    P1: "Snake Plant",
    P2: "ZZ Plant",
    P3: "Agalonema",
    P4: "Dieffenbachia",
    P5: "Syngonium",
  },
  {
    Q1: "Living Room",
    Q2: "Not a lot of natural sunlight",
    Q3: "Green thumb with few houseplants",
    Q4: "No",
    Q5: "Sometimes",
    P1: "Aglaonema",
    P2: "Money Plant",
    P3: "Dieffenbachia",
    P4: "English Ivy",
    P5: "Syngonium",
  },
  {
    Q1: "Living Room",
    Q2: "Not a lot of natural sunlight",
    Q3: "First time budding plant mom/dad",
    Q4: "Yes",
    Q5: "Yes",
    P1: "Table Palm",
    P2: "Maranta",
    P3: "Rhapis Lady Palm",
    P4: "Table Palm",
    P5: "Impatiens",
  },
  {
    Q1: "Living Room",
    Q2: "Not a lot of natural sunlight",
    Q3: "First time budding plant mom/dad",
    Q4: "Yes",
    Q5: "No",
    P1: "Ruffled Fan Palm",
    P2: "Calathea",
    P3: "Table Palm",
    P4: "Rhapis Lady Palm",
    P5: "Impatiens",
  },
  {
    Q1: "Living Room",
    Q2: "Not a lot of natural sunlight",
    Q3: "First time budding plant mom/dad",
    Q4: "Yes",
    Q5: "Sometimes",
    P1: "Areca Palm",
    P2: "Calathea",
    P3: "Rhapis Lady Palm",
    P4: "Table Palm",
    P5: "Water Bamboo",
  },
  {
    Q1: "Living Room",
    Q2: "Not a lot of natural sunlight",
    Q3: "First time budding plant mom/dad",
    Q4: "No",
    Q5: "Yes",
    P1: "Aglaonema",
    P2: "Dieffenbachia",
    P3: "Money Plant",
    P4: "Syngonium",
    P5: "Table Palm",
  },
  {
    Q1: "Living Room",
    Q2: "Not a lot of natural sunlight",
    Q3: "First time budding plant mom/dad",
    Q4: "No",
    Q5: "No",
    P1: "Snake Plant",
    P2: "ZZ Plant",
    P3: "Agalonema",
    P4: "Dieffenbachia",
    P5: "Syngonium",
  },
  {
    Q1: "Living Room",
    Q2: "Not a lot of natural sunlight",
    Q3: "First time budding plant mom/dad",
    Q4: "No",
    Q5: "Sometimes",
    P1: "Aglaonema",
    P2: "Money Plant",
    P3: "Dieffenbachia",
    P4: "English Ivy",
    P5: "Syngonium",
  },
  {
    Q1: "Living Room",
    Q2: "Not a lot of natural sunlight",
    Q3: "Most of my plants are dead :(",
    Q4: "Yes",
    Q5: "Yes",
    P1: "Table Palm",
    P2: "Rhapis Lady Palm",
    P3: "Impatiens",
    P4: "Water Bamboo",
    P5: "Maranta",
  },
  {
    Q1: "Living Room",
    Q2: "Not a lot of natural sunlight",
    Q3: "Most of my plants are dead :(",
    Q4: "Yes",
    Q5: "No",
    P1: "Spider Plant",
    P2: "Hypoestes",
    P3: "Rhapis lady Palm",
    P4: "Table Palm",
    P5: "Syngonium",
  },
  {
    Q1: "Living Room",
    Q2: "Not a lot of natural sunlight",
    Q3: "Most of my plants are dead :(",
    Q4: "Yes",
    Q5: "Sometimes",
    P1: "Ruffled Fan Palm",
    P2: "Rhapis Lady Palm",
    P3: "Table Palm",
    P4: "Water Bamboo",
    P5: "Maranta",
  },
  {
    Q1: "Living Room",
    Q2: "Not a lot of natural sunlight",
    Q3: "Most of my plants are dead :(",
    Q4: "No",
    Q5: "Yes",
    P1: "Aglaonema",
    P2: "Dieffenbachia",
    P3: "Money Plant",
    P4: "Syngonium",
    P5: "Table Palm",
  },
  {
    Q1: "Living Room",
    Q2: "Not a lot of natural sunlight",
    Q3: "Most of my plants are dead :(",
    Q4: "No",
    Q5: "No",
    P1: "Snake Plant",
    P2: "ZZ Plant",
    P3: "Agalonema",
    P4: "Dieffenbachia",
    P5: "Syngonium",
  },
  {
    Q1: "Living Room",
    Q2: "Not a lot of natural sunlight",
    Q3: "Most of my plants are dead :(",
    Q4: "No",
    Q5: "Sometimes",
    P1: "Aglaonema",
    P2: "Money Plant",
    P3: "Dieffenbachia",
    P4: "English Ivy",
    P5: "Syngonium",
  },
  {
    Q1: "Living Room",
    Q2: "I’m not sure",
    Q3: "Total plant savant and experienced plant-parent",
    Q4: "Yes",
    Q5: "Yes",
    P1: "Areca Palm",
    P2: "Table Palm",
    P3: "Succulents",
    P4: "Water Bamboo",
    P5: "Ruffled Fan Palm",
  },
  {
    Q1: "Living Room",
    Q2: "I’m not sure",
    Q3: "Total plant savant and experienced plant-parent",
    Q4: "Yes",
    Q5: "No",
    P1: "Spider Plant",
    P2: "Areca Palm",
    P3: "Ferns",
    P4: "Maranta",
    P5: "Hypoestes",
  },
  {
    Q1: "Living Room",
    Q2: "I’m not sure",
    Q3: "Total plant savant and experienced plant-parent",
    Q4: "Yes",
    Q5: "Sometimes",
    P1: "Rhapis Lady Palm",
    P2: "Succulent Bush",
    P3: "Carpet Sedum",
    P4: "Spider Plant",
    P5: "Ruffled Fan Palm",
  },
  {
    Q1: "Living Room",
    Q2: "I’m not sure",
    Q3: "Total plant savant and experienced plant-parent",
    Q4: "No",
    Q5: "Yes",
    P1: "Table Palm",
    P2: "Rhapis Lady Palm",
    P3: "Impatiens",
    P4: "Water Bamboo",
    P5: "Maranta",
  },
  {
    Q1: "Living Room",
    Q2: "I’m not sure",
    Q3: "Total plant savant and experienced plant-parent",
    Q4: "No",
    Q5: "No",
    P1: "Spider Plant",
    P2: "Hypoestes",
    P3: "Rhapis lady Palm",
    P4: "Table Palm",
    P5: "Syngonium",
  },
  {
    Q1: "Living Room",
    Q2: "I’m not sure",
    Q3: "Total plant savant and experienced plant-parent",
    Q4: "No",
    Q5: "Sometimes",
    P1: "Ruffled Fan Palm",
    P2: "Rhapis Lady Palm",
    P3: "Table Palm",
    P4: "Water Bamboo",
    P5: "Maranta",
  },
  {
    Q1: "Living Room",
    Q2: "I’m not sure",
    Q3: "Green thumb with few houseplants",
    Q4: "Yes",
    Q5: "Yes",
    P1: "Herbs",
    P2: "Mini Tree Fern",
    P3: "Succulents",
    P4: "Song of India",
    P5: "Dracaena",
  },
  {
    Q1: "Living Room",
    Q2: "I’m not sure",
    Q3: "Green thumb with few houseplants",
    Q4: "Yes",
    Q5: "No",
    P1: "Spider Plant",
    P2: "Succulent Bush",
    P3: "Areca Palm",
    P4: "Chrysanthemum",
    P5: "Petunia",
  },
  {
    Q1: "Living Room",
    Q2: "I’m not sure",
    Q3: "Green thumb with few houseplants",
    Q4: "Yes",
    Q5: "Sometimes",
    P1: "Maranta",
    P2: "Calathea",
    P3: "Table Palm",
    P4: "Gerbera",
    P5: "Petunia",
  },
  {
    Q1: "Living Room",
    Q2: "I’m not sure",
    Q3: "Green thumb with few houseplants",
    Q4: "No",
    Q5: "Yes",
    P1: "Raindrop Peperomia",
    P2: "Pink Anthurium",
    P3: "Japanese Spindletree",
    P4: "String of Pearls",
    P5: "Pink Anthurium",
  },
  {
    Q1: "Living Room",
    Q2: "I’m not sure",
    Q3: "Green thumb with few houseplants",
    Q4: "No",
    Q5: "No",
    P1: "Ribbonbush Plant",
    P2: "Japanese Spindletree",
    P3: "Ribbonbush Plant",
    P4: "Wandering Jew",
    P5: "String of Pearls",
  },
  {
    Q1: "Living Room",
    Q2: "I’m not sure",
    Q3: "Green thumb with few houseplants",
    Q4: "No",
    Q5: "Sometimes",
    P1: "Dracaena Fragrans",
    P2: "String of Pearls",
    P3: "Raindrop Peperomia",
    P4: "Pink Anthurium",
    P5: "Japanese Spindletree",
  },
  {
    Q1: "Living Room",
    Q2: "I’m not sure",
    Q3: "First time budding plant mom/dad",
    Q4: "Yes",
    Q5: "Yes",
    P1: "Areca Palm",
    P2: "Table Palm",
    P3: "Succulents",
    P4: "Water Bamboo",
    P5: "Ruffled Fan Palm",
  },
  {
    Q1: "Living Room",
    Q2: "I’m not sure",
    Q3: "First time budding plant mom/dad",
    Q4: "Yes",
    Q5: "No",
    P1: "Spider Plant",
    P2: "Areca Palm",
    P3: "Ferns",
    P4: "Maranta",
    P5: "Hypoestes",
  },
  {
    Q1: "Living Room",
    Q2: "I’m not sure",
    Q3: "First time budding plant mom/dad",
    Q4: "Yes",
    Q5: "Sometimes",
    P1: "Rhapis Lady Palm",
    P2: "Succulent Bush",
    P3: "Carpet Sedum",
    P4: "Spider Plant",
    P5: "Ruffled Fan Palm",
  },
  {
    Q1: "Living Room",
    Q2: "I’m not sure",
    Q3: "First time budding plant mom/dad",
    Q4: "No",
    Q5: "Yes",
    P1: "Japanese Spindletree",
    P2: "Ribbonbush Plant",
    P3: "String of Pearls",
    P4: "Boston Fern",
    P5: "Pink Anthurium",
  },
  {
    Q1: "Living Room",
    Q2: "I’m not sure",
    Q3: "First time budding plant mom/dad",
    Q4: "No",
    Q5: "No",
    P1: "Raindrop Peperomia",
    P2: "Pink Anthurium",
    P3: "Japanese Spindletree",
    P4: "String of Pearls",
    P5: "Raindrop Peperomia",
  },
  {
    Q1: "Living Room",
    Q2: "I’m not sure",
    Q3: "First time budding plant mom/dad",
    Q4: "No",
    Q5: "Sometimes",
    P1: "Dracaena Fragrans",
    P2: "Wandering Jew",
    P3: "String of Pearls",
    P4: "Wandering Jew",
    P5: "Japanese Spindletree",
  },
  {
    Q1: "Living Room",
    Q2: "I’m not sure",
    Q3: "Most of my plants are dead :(",
    Q4: "Yes",
    Q5: "Yes",
    P1: "Herbs",
    P2: "Mini Tree Fern",
    P3: "Succulents",
    P4: "Song of India",
    P5: "Dracaena",
  },
  {
    Q1: "Living Room",
    Q2: "I’m not sure",
    Q3: "Most of my plants are dead :(",
    Q4: "Yes",
    Q5: "No",
    P1: "Spider Plant",
    P2: "Succulent Bush",
    P3: "Areca Palm",
    P4: "Chrysanthemum",
    P5: "Petunia",
  },
  {
    Q1: "Living Room",
    Q2: "I’m not sure",
    Q3: "Most of my plants are dead :(",
    Q4: "Yes",
    Q5: "Sometimes",
    P1: "Maranta",
    P2: "Calathea",
    P3: "Table Palm",
    P4: "Gerbera",
    P5: "Petunia",
  },
  {
    Q1: "Living Room",
    Q2: "I’m not sure",
    Q3: "Most of my plants are dead :(",
    Q4: "No",
    Q5: "Yes",
    P1: "Raindrop Peperomia",
    P2: "Pink Anthurium",
    P3: "Japanese Spindletree",
    P4: "String of Pearls",
    P5: "Pink Anthurium",
  },
  {
    Q1: "Living Room",
    Q2: "I’m not sure",
    Q3: "Most of my plants are dead :(",
    Q4: "No",
    Q5: "No",
    P1: "Ribbonbush Plant",
    P2: "Japanese Spindletree",
    P3: "Ribbonbush Plant",
    P4: "Wandering Jew",
    P5: "String of Pearls",
  },
  {
    Q1: "Living Room",
    Q2: "I’m not sure",
    Q3: "Most of my plants are dead :(",
    Q4: "No",
    Q5: "Sometimes",
    P1: "Dracaena Fragrans",
    P2: "String of Pearls",
    P3: "Raindrop Peperomia",
    P4: "Pink Anthurium",
    P5: "Japanese Spindletree",
  },
];

var object = {
  "Which room are you looking to put plants in?": {
    "Living Room": "",
    Bedroom: "",
    Hallway: "",
    Kitchen: "",
    "Child's Room": "",
    Bathroom: "",
    Office: "",
    Balcony: "",
  },
};

var object1 = {
  "What kind of light does this area get?": {
    "Bright direct sunlight 4-5 hours per day": "",
    "Indirect or filtered sunlight throughout the day": "",
    "Not a lot of natural sunlight": "",
    "I’m not sure": "",
  },
};

var object2 = {
  "What's your experience with plants?": {
    "Total plant savant and experienced plant-parent": "",
    "Green thumb with few houseplants": "",
    "First time budding plant mom/dad": "",
    "Most of my plants are dead :(": "",
  },
};

var object3 = {
  "Do you have any pets or children?": {
    Yes: "",
    No: "",
  },
};

var object4 = {
  "Do you travel often, or are you likely to forget watering your plants?": {
    Yes: "",
    No: "",
    Sometimes: "",
  },
};

let arr = [];

function clicklistner(e) {
  while (div.firstChild) {
    div.removeChild(div.lastChild);
  }
  console.log(e.target.dataset.ans);
  buttons(e.target.dataset.ans);
  arr.push(e.target.dataset.ans);
  console.log(arr);
  

  if (count === 6) {
    document.getElementById("h1").remove();
    image.remove();
    document.getElementById("row").remove();
    secondpage.style.display = "block";
    let newArray = Answers.find(
      (element) =>
        element.Q1 === arr[0] &&
        element.Q2 === arr[1] &&
        element.Q3 === arr[2] &&
        element.Q4 === arr[3] &&
        element.Q5 === arr[4]
    );
    console.log(arr[0]);
    console.log(newArray);
    console.log(
      newArray.P1,
      newArray.P2,
      newArray.P3,
      newArray.P4,
      newArray.P5
    );
    document.getElementById("modalimg-1").src = "./img/ezgif.com-gif-maker.jpg"
  }
}

let count = 0;
let secondpage = document.getElementById("secondpage");
let div = document.getElementById("root");
let heading = document.getElementById("h1");
let image = document.getElementById("myimg");
secondpage.style.display = "none";
let n = [
  object[Object.keys(object)[0]],
  object1[Object.keys(object1)[0]],
  object2[Object.keys(object2)[0]],
  object3[Object.keys(object3)[0]],
  object4[Object.keys(object4)[0]],
];
function buttons() {
  for (let que in n[count]) {
    if (count === 0) {
      heading.innerHTML = Object.keys(object)[0];
      image.src = "./img/pexels-ylanite-koppens-796620.jpg";
    } else if (count === 1) {
      heading.innerHTML = Object.keys(object1)[0];
      image.src = "./img/pepper-face-plant-small-pot-min.jpg";
    } else if (count === 2) {
      heading.innerHTML = Object.keys(object2)[0];
      image.src = "./img/snake-plant-white-pot-min.jpg";
    } else if (count === 3) {
      heading.innerHTML = Object.keys(object3)[0];
      image.src = "./img/pexels-ylanite-koppens-776656.jpg";
    } else if (count === 4) {
      heading.innerHTML = Object.keys(object4)[0];
      image.src = "./img/green-houseplant-glass-jar-min (1).jpg";
    }
    let button = document.createElement("button");
    button.classList.add("btn");
    button.classList.add("btn-dark");
    button.innerHTML = que;
    button.dataset.ans = que;
    button.onclick = clicklistner;
    div.appendChild(button);
  }

  count++;
}
buttons();

// modal section here
if (count === 6) {
  document.getElementById("exampleModal").style.display = "none";
  let something = (document.getElementById("exampleModal").style.display =
    "block");

  document.getElementById("submitButton").onclick = something;
}

//  Array section here
